# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shrinky_pic_gui.ui'
#
# Created: Thu Dec  5 20:26:08 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.resize(358, 336)
		self.horizontalLayout = QtGui.QHBoxLayout(Form)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.gridLayout = QtGui.QGridLayout()
		self.gridLayout.setObjectName("gridLayout")
		self.CancelButton = QtGui.QPushButton(Form)
		self.CancelButton.setObjectName("CancelButton")
		self.gridLayout.addWidget(self.CancelButton, 8, 1, 1, 2)
		self.GetPictureButton = QtGui.QPushButton(Form)
		self.GetPictureButton.setObjectName("GetPictureButton")
		self.gridLayout.addWidget(self.GetPictureButton, 1, 2, 1, 1)
		self.PictureRotationLabel = QtGui.QLabel(Form)
		self.PictureRotationLabel.setObjectName("PictureRotationLabel")
		self.gridLayout.addWidget(self.PictureRotationLabel, 4, 0, 1, 1)
		self.OkButton = QtGui.QPushButton(Form)
		self.OkButton.setObjectName("OkButton")
		self.gridLayout.addWidget(self.OkButton, 8, 0, 1, 1)
		self.FileNameLabel = QtGui.QLabel(Form)
		self.FileNameLabel.setObjectName("FileNameLabel")
		self.gridLayout.addWidget(self.FileNameLabel, 0, 0, 1, 1)
		self.CaptionEdit = QtGui.QLineEdit(Form)
		self.CaptionEdit.setObjectName("CaptionEdit")
		self.gridLayout.addWidget(self.CaptionEdit, 7, 0, 1, 3)
		self.SizeSelect = QtGui.QComboBox(Form)
		self.SizeSelect.setObjectName("SizeSelect")
		self.SizeSelect.addItem("")
		self.SizeSelect.addItem("")
		self.SizeSelect.addItem("")
		self.gridLayout.addWidget(self.SizeSelect, 3, 0, 1, 1)
		self.CaptionLabel = QtGui.QLabel(Form)
		self.CaptionLabel.setObjectName("CaptionLabel")
		self.gridLayout.addWidget(self.CaptionLabel, 6, 0, 1, 1)
		self.FileNameEdit = QtGui.QLineEdit(Form)
		self.FileNameEdit.setObjectName("FileNameEdit")
		self.gridLayout.addWidget(self.FileNameEdit, 1, 0, 1, 2)
		self.PictureSizeLabel = QtGui.QLabel(Form)
		self.PictureSizeLabel.setObjectName("PictureSizeLabel")
		self.gridLayout.addWidget(self.PictureSizeLabel, 2, 0, 1, 1)
		self.RotationBox = QtGui.QSpinBox(Form)
		self.RotationBox.setMinimum(-20)
		self.RotationBox.setMaximum(20)
		self.RotationBox.setObjectName("RotationBox")
		self.gridLayout.addWidget(self.RotationBox, 5, 0, 1, 1)
		self.RotationSlider = QtGui.QSlider(Form)
		self.RotationSlider.setMinimum(-15)
		self.RotationSlider.setMaximum(15)
		self.RotationSlider.setSingleStep(0)
		self.RotationSlider.setProperty("value", 0)
		self.RotationSlider.setSliderPosition(0)
		self.RotationSlider.setOrientation(QtCore.Qt.Horizontal)
		self.RotationSlider.setTickPosition(QtGui.QSlider.TicksAbove)
		self.RotationSlider.setObjectName("RotationSlider")
		self.gridLayout.addWidget(self.RotationSlider, 5, 1, 1, 2)
		self.horizontalLayout.addLayout(self.gridLayout)

		self.retranslateUi(Form)
		QtCore.QObject.connect(self.RotationBox, QtCore.SIGNAL("valueChanged(int)"), self.RotationSlider.setValue)
		QtCore.QObject.connect(self.RotationSlider, QtCore.SIGNAL("sliderMoved(int)"), self.RotationBox.setValue)
#        QtCore.QObject.connect(self.OkButton, QtCore.SIGNAL("pressed()"), Form.setupUi)
#        QtCore.QObject.connect(self.CaptionEdit, QtCore.SIGNAL("textChanged(QString)"), Form.setupUi)
#        QtCore.QObject.connect(self.GetPictureButton, QtCore.SIGNAL("clicked()"), Form.setupUi)
		QtCore.QObject.connect(self.CancelButton, QtCore.SIGNAL("clicked()"), Form.close)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		Form.setWindowTitle(QtGui.QApplication.translate("Form", "ShrinkyPic", None, QtGui.QApplication.UnicodeUTF8))
		self.CancelButton.setText(QtGui.QApplication.translate("Form", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
		self.GetPictureButton.setText(QtGui.QApplication.translate("Form", "Get Picture", None, QtGui.QApplication.UnicodeUTF8))
		self.PictureRotationLabel.setText(QtGui.QApplication.translate("Form", "Picture Rotation", None, QtGui.QApplication.UnicodeUTF8))
		self.OkButton.setText(QtGui.QApplication.translate("Form", "OK", None, QtGui.QApplication.UnicodeUTF8))
		self.FileNameLabel.setText(QtGui.QApplication.translate("Form", "File Name", None, QtGui.QApplication.UnicodeUTF8))
		self.CaptionEdit.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Enter a caption for this picture.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.SizeSelect.setItemText(0, QtGui.QApplication.translate("Form", "Small", None, QtGui.QApplication.UnicodeUTF8))
		self.SizeSelect.setItemText(1, QtGui.QApplication.translate("Form", "Medium", None, QtGui.QApplication.UnicodeUTF8))
		self.SizeSelect.setItemText(2, QtGui.QApplication.translate("Form", "Large", None, QtGui.QApplication.UnicodeUTF8))
		self.CaptionLabel.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Enter a caption for this picture.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.CaptionLabel.setText(QtGui.QApplication.translate("Form", "Caption", None, QtGui.QApplication.UnicodeUTF8))
		self.PictureSizeLabel.setText(QtGui.QApplication.translate("Form", "Picture Size", None, QtGui.QApplication.UnicodeUTF8))

